### ISSUE TITLE
Upgrade Next.js

### ISSUE THREAD

**Issue by io-kobayashiii** [io-kobayashiii/techblog#166]

**Comment by io-kobayashiii** [comment]
Errors occur

> error Failed to download `M PLUS 1p` from Google Fonts. Using fallback font instead.
AbortError: The user aborted a request.
    at abort (/Users/kobayashi/git/io-kobayashiii/techblog/node_modules/next/dist/compiled/node-fetch/index.js:1:65190)
    at EventTarget.abortAndFinalize (/Users/kobayashi/git/io-kobayashiii/techblog/node_modules/next/dist/compiled/node-fetch/index.js:1:65410)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at EventTarget.dispatchEvent (node:internal/event_target:679:26)
    at abortSignal (node:internal/abort_controller:314:10)
    at AbortController.abort (node:internal/abort_controller:344:5)
    at Timeout.<anonymous> (/Users/kobayashi/git/io-kobayashiii/techblog/node_modules/next/dist/compiled/@next/font/dist/google/fetch-css-from-google-fonts.js:35:55)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  type: 'aborted'

- https://github.com/vercel/next.js/issues/45080
